spring.application.name=proyecto-titulo

jwt.secret=titulo-proyecto-2022668-secret-password
jwt.expiration=86400000


server.port=8081

# Configuracion de Gmail-SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:PENDIENTE}
spring.mail.password=${MAIL_PASSWORD:PENDIENTE}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=UTF-8


# BD
# BD Dinámica para Local y Docker
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:agricola_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:admin123}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Subida de los archivos
app.upload.dir=uploads/facturas
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB